import Link from 'next/link';
import { redirect } from 'next/navigation';
import { Activity, ArrowUpRight, Car, CircleDollarSign, Users } from 'lucide-react';
import { getCurrentUser } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { formatCurrency } from '@/lib/utils';

export const dynamic = 'force-dynamic';
export default async function AdminDashboard() { const user = await getCurrentUser(); if (!user || !['ADMIN', 'STAFF'].includes(user.role.name)) redirect('/dashboard'); const [vehicles, customers, active, revenue] = await Promise.all([prisma.vehicle.count(), prisma.user.count({ where: { role: { name: 'CUSTOMER' } } }), prisma.booking.count({ where: { status: { in: ['CONFIRMED', 'ACTIVE'] } } }), prisma.booking.aggregate({ _sum: { totalAmount: true }, where: { status: { not: 'CANCELLED' } } })]); return <main className="min-h-screen bg-ink px-6 py-12 text-paper"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-lime">Operations console</p><h1 className="mt-3 font-display text-5xl">Good morning, {user.name.split(' ')[0]}.</h1></div><Link href="/cars" className="flex items-center gap-2 rounded-full bg-lime px-5 py-3 font-semibold text-ink">View customer site <ArrowUpRight size={16} /></Link></div><div className="mt-12 grid gap-4 md:grid-cols-4"><Stat icon={<Car />} label="Fleet" value={vehicles} /><Stat icon={<Users />} label="Customers" value={customers} /><Stat icon={<Activity />} label="Active rentals" value={active} /><Stat icon={<CircleDollarSign />} label="Revenue" value={formatCurrency(revenue._sum.totalAmount || 0)} /></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl bg-paper p-7 text-ink"><h2 className="font-display text-3xl">Today's focus</h2><div className="mt-6 space-y-4"><Row title="Booking operations" detail="Review pending reservations and keep the fleet moving." href="/dashboard" /><Row title="Fleet health" detail="Inspect availability and upcoming maintenance windows." href="/cars" /><Row title="Customer care" detail="Keep every handoff as thoughtful as the first." href="/dashboard" /></div></div><div className="rounded-2xl border border-paper/15 p-7"><p className="text-sm text-paper/50">Live workspace</p><h2 className="mt-2 font-display text-3xl">Everything in motion.</h2><p className="mt-4 leading-7 text-paper/60">The operations layer is connected to the same booking and fleet records customers see.</p></div></div></div></main>; }
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number | string }) { return <div className="rounded-2xl border border-paper/15 p-5"><div className="text-lime">{icon}</div><p className="mt-7 text-sm text-paper/50">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p></div>; }
function Row({ title, detail, href }: { title: string; detail: string; href: string }) { return <Link href={href} className="flex items-center justify-between gap-4 border-b border-ink/10 pb-4"><span><strong className="block">{title}</strong><small className="text-ink/55">{detail}</small></span><ArrowUpRight size={18} className="text-moss" /></Link>; }
