import Link from 'next/link';
import { ArrowUpRight, CalendarDays, Car, CircleDollarSign } from 'lucide-react';
import { getCurrentUser } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { formatCurrency } from '@/lib/utils';

export const dynamic = 'force-dynamic';

export default async function Dashboard() { const user = await getCurrentUser(); if (!user) return <main className="mx-auto max-w-xl px-6 py-24 text-center"><h1 className="font-display text-5xl">Your drive starts here.</h1><p className="mt-4 text-ink/60">Sign in to see bookings, payments, and saved journeys.</p><Link href="/login" className="mt-8 inline-flex rounded-full bg-ink px-6 py-3 font-semibold text-paper">Sign in</Link></main>; const bookings = await prisma.booking.findMany({ where: { userId: user.id }, include: { vehicle: true }, orderBy: { pickupAt: 'asc' }, take: 5 }); const spend = bookings.reduce((total, booking) => total + booking.totalAmount, 0); return <main className="min-h-screen px-6 py-14"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-moss">Personal dashboard</p><h1 className="mt-3 font-display text-5xl">Good to see you, {user.name.split(' ')[0]}.</h1><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-moss p-6 text-paper"><CalendarDays className="text-lime" /><p className="mt-8 text-sm text-paper/60">Total bookings</p><p className="mt-1 text-4xl font-semibold">{bookings.length}</p></div><div className="rounded-2xl bg-white p-6 ring-1 ring-ink/10"><Car className="text-moss" /><p className="mt-8 text-sm text-ink/50">Upcoming journeys</p><p className="mt-1 text-4xl font-semibold">{bookings.filter((booking) => booking.pickupAt > new Date()).length}</p></div><div className="rounded-2xl bg-lime p-6"><CircleDollarSign /><p className="mt-8 text-sm text-ink/60">Total spend</p><p className="mt-1 text-4xl font-semibold">{formatCurrency(spend)}</p></div></div><section className="mt-14 rounded-2xl bg-white p-6 ring-1 ring-ink/10"><div className="flex justify-between"><h2 className="font-display text-3xl">Your journeys</h2><Link href="/cars" className="flex items-center gap-1 text-sm font-semibold text-moss">Book a car <ArrowUpRight size={16} /></Link></div><div className="mt-6 divide-y divide-ink/10">{bookings.map((booking) => <div key={booking.id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div><p className="font-semibold">{booking.vehicle.brand} {booking.vehicle.model}</p><p className="mt-1 text-sm text-ink/50">{booking.pickupLocation} · {booking.pickupAt.toLocaleDateString('en-IN')}</p></div><span className="rounded-full bg-lime/60 px-3 py-1 text-xs font-bold">{booking.status}</span></div>)}{!bookings.length && <p className="py-8 text-ink/50">No journeys yet. The open road is waiting.</p>}</div></section></div></main>; }
