import Link from 'next/link';
import { ArrowUpRight, Fuel, Settings2, Users } from 'lucide-react';
import { prisma } from '@/lib/prisma';
import { formatCurrency } from '@/lib/utils';

export const dynamic = 'force-dynamic';

export default async function CarsPage({ searchParams }: { searchParams: Promise<{ category?: string; location?: string }> }) {
  const params = await searchParams;
  const vehicles = await prisma.vehicle.findMany({ where: { status: 'AVAILABLE', ...(params.location ? { location: { contains: params.location, mode: 'insensitive' } } : {}), ...(params.category ? { category: { name: params.category } } : {}) }, include: { category: true, images: { take: 1, orderBy: { sortOrder: 'asc' } } }, orderBy: { dailyPrice: 'asc' } }).catch(() => []);
  const categories = await prisma.category.findMany({ orderBy: { name: 'asc' } }).catch(() => []);
  return <main className="min-h-screen px-6 py-14"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-moss">The collection</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><h1 className="font-display text-5xl">Find your next <em>good drive.</em></h1><p className="max-w-sm text-ink/60">Simple booking, honest pricing, and a car for every version of the weekend.</p></div><form className="mt-10 grid gap-3 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-ink/10 md:grid-cols-[1fr_1fr_auto]"><input name="location" defaultValue={params.location} placeholder="Pickup location" className="rounded-xl bg-paper px-4 py-3 outline-none ring-1 ring-ink/10 focus:ring-moss" /><select name="category" defaultValue={params.category || ''} className="rounded-xl bg-paper px-4 py-3 outline-none ring-1 ring-ink/10"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select><button className="rounded-xl bg-ink px-7 py-3 font-semibold text-paper hover:bg-moss">Search</button></form><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{vehicles.map((vehicle) => <article key={vehicle.id} className="group overflow-hidden rounded-2xl border border-ink/10 bg-white"><div className="relative h-60 bg-ink/5">{vehicle.images[0] && <img src={vehicle.images[0].url} alt={vehicle.images[0].alt || `${vehicle.brand} ${vehicle.model}`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" />}<span className="absolute left-4 top-4 rounded-full bg-lime px-3 py-1 text-xs font-bold">Available</span></div><div className="p-6"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-moss">{vehicle.category.name} · {vehicle.year}</p><h2 className="mt-1 font-display text-3xl">{vehicle.brand} {vehicle.model}</h2></div><Link href={`/cars/${vehicle.id}`} className="self-end rounded-full bg-ink p-3 text-paper"><ArrowUpRight size={18} /></Link></div><div className="mt-6 grid grid-cols-3 border-y border-ink/10 py-4 text-xs text-ink/60"><span className="flex items-center gap-1"><Settings2 size={14} /> {vehicle.transmission.toLowerCase()}</span><span className="flex items-center gap-1"><Fuel size={14} /> {vehicle.fuelType.toLowerCase()}</span><span className="flex items-center gap-1"><Users size={14} /> {vehicle.seats} seats</span></div><p className="mt-5 font-semibold">{formatCurrency(vehicle.dailyPrice)} <span className="font-normal text-ink/50">/ day</span></p></div></article>)}{!vehicles.length && <p className="col-span-full rounded-2xl border border-dashed border-ink/20 p-12 text-center text-ink/60">No vehicles found. Try another location or category.</p>}</div></div></main>;
}
